services:
  mongo:
    image: mongo:4.4.6
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"  # Asegúrate de que haya comillas y espacio después del guion
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name:  mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"  # Asegúrate de que haya comillas y espacio después del guion
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_BASICAUTH: "false"
  api:
    build: .
    tty: true
    container_name: API
    working_dir: /Dockerbuildfiles
    image: node:18-alpine
    command: "npm install dotenv && npm install express && npm install mongoose && node api.js"
    ports:
      - "3000:3000"  # Asegúrate de que haya un espacio después del guion
    env_file:
      - .env
    environment:
      - MONGO_URI=${ME_CONFIG_MONGODB_URL}
    depends_on:
      - mongo-express

