services:
  mongo:
    image: mongo:4.4.6
    restart: always
    container_name: mongo
    ports:
      - ${MONGO_PORT}  
    expose:
      - ${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongoStorageVol:/data/db:rw

  mongo-express:
    image: mongo-express
    container_name:  mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT} 
    expose:
      - ${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_BASICAUTH: "false"
  node-api:
    tty: true
    image: node:18-alpine
    container_name: node-api
    build: .
    working_dir: /DevOpsProject
    ports:
      - ${NODE_SERVICE_PORT}
    environment:
      NODE_SERVICE_PORT: ${NODE_SERVICE_PORT}
    depends_on:
      - mongo-express
volumes:
  mongoStorageVol:
    driver: local 